on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Prepare
        id: prep
        run: cd server-admin && ./scripts/getversion.sh
      - name: Build mods
        run: |
          npm run build:mods
      - name: Zip it
        run: |
          for mod in $(ls mods); do echo $mod; zip -r $mod mods/$mod/build; done
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.prep.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            *.zip
